// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6tAXmwTCXZ8V9-f7Qk-2O85T-CR0QBC0',
    appId: '1:223981517135:web:55257d77a65fc7060f6d3a',
    messagingSenderId: '223981517135',
    projectId: 'albaher-53911',
    authDomain: 'albaher-53911.firebaseapp.com',
    storageBucket: 'albaher-53911.appspot.com',
    measurementId: 'G-JF227CXGXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7H3mDHvcJiIF96OgMz5nJpgpJeB08pOo',
    appId: '1:223981517135:android:15f7c536bcd143c50f6d3a',
    messagingSenderId: '223981517135',
    projectId: 'albaher-53911',
    storageBucket: 'albaher-53911.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD49zAjmeNWppJEhy_b3LbVFvWLk4A4BCw',
    appId: '1:223981517135:ios:f379c1c0d56c6f1b0f6d3a',
    messagingSenderId: '223981517135',
    projectId: 'albaher-53911',
    storageBucket: 'albaher-53911.appspot.com',
    iosBundleId: 'com.example.sharedPrefrenceTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD49zAjmeNWppJEhy_b3LbVFvWLk4A4BCw',
    appId: '1:223981517135:ios:f379c1c0d56c6f1b0f6d3a',
    messagingSenderId: '223981517135',
    projectId: 'albaher-53911',
    storageBucket: 'albaher-53911.appspot.com',
    iosBundleId: 'com.example.sharedPrefrenceTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6tAXmwTCXZ8V9-f7Qk-2O85T-CR0QBC0',
    appId: '1:223981517135:web:790c484794f953010f6d3a',
    messagingSenderId: '223981517135',
    projectId: 'albaher-53911',
    authDomain: 'albaher-53911.firebaseapp.com',
    storageBucket: 'albaher-53911.appspot.com',
    measurementId: 'G-M7RK64Z376',
  );
}
